# wrangler.toml

name = "my-fastapi-app" # Name of your Cloudflare Worker
type = "javascript" # Specifies the worker type; necessary for Python compatibility

# Entry-point of your FastAPI application
main = "./main.py"  # Replace with the actual path to your main file

workers_dev = true # Set to `true` for development deployment
compatibility_date = "2024-11-14" # Use today's date or the date of initial deployment

